spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      seata: false
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.omind-user-plat.url}
          username: ${datasource.omind-user-plat.username}
          password: ${datasource.omind-user-plat.password}

wx:
  miniapp:
    appid: wx66a19ee384891552
    secret: ba978615ad3666101a14e2ec6514b764
    token: omind2023
    aesKey: rA5bUXwCPrSnicABarl6rLGm9BWGBnvkIG9TPzjt2ae
    msgDataFormat: JSON
  pay:
    mchId: 1638720029
    mchKey: 0lKdF0C3kfxeweg2ySf61e67b0ml3Wik
    keyPath: classpath:/resources/omind_apiclient_cert.p12
    isSandbox: true
    payCallback: https://127.0.0.1:8080/mp/v1/pay/wx



xxl:
  job:
    admin:
      addresses: http://172.25.0.9:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: omind-scheduler-mp
      address:
      ip:
      port: 18087
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30